// Generated by https://quicktype.io

export class GeoTopArtists {
    topartists: Topartists = new Topartists();
}

export class Topartists {
    artist:  Artist[] = [];
    "@attr": Attr;
}

export interface Attr {
    country:    string;
    page:       string;
    perPage:    string;
    totalPages: string;
    total:      string;
}

export interface Artist {
    name:       string;
    listeners:  string;
    mbid:       string;
    url:        string;
    streamable: string;
    image:      Image[];
}

export interface Image {
    "#text": string;
    size:    Size;
}

export enum Size {
    Extralarge = "extralarge",
    Large = "large",
    Medium = "medium",
    Mega = "mega",
    Small = "small",
}
