// Generated by https://quicktype.io

export interface Results {
    results: Results;
}

export interface Results {
    "opensearch:Query":        OpensearchQuery;
    "opensearch:totalResults": string;
    "opensearch:startIndex":   string;
    "opensearch:itemsPerPage": string;
    artistmatches:             Artistmatches;
    "@attr":                   Attr;
}

export interface Attr {
    for: string;
}

export interface Artistmatches {
    artist: Artist[];
}

export interface Artist {
    name:       string;
    listeners:  string;
    mbid:       string;
    url:        string;
    streamable: string;
    image:      Image[];
}

export interface Image {
    "#text": string;
    size:    Size;
}

export enum Size {
    Extralarge = "extralarge",
    Large = "large",
    Medium = "medium",
    Mega = "mega",
    Small = "small",
}

export interface OpensearchQuery {
    "#text":     string;
    role:        string;
    searchTerms: string;
    startPage:   string;
}
